### ISSUE TITLE
Need help with setup instructions

### ISSUE THREAD

**Issue by ahemanna** [mertbakir/resume-a4#1]
Hi @mertbakir, thanks for putting this together.

I'm trying to follow your instructions in the README.md file and there appears to be a typo under the Start section here - https://github.com/mertbakir/resume-a4?tab=readme-ov-file#start . Step 1, says `Copy config.yaml from exampleSite to the root directory of your hugo project.` but I don't see a config.yaml file under the exampleSite. Did you mean the root directory of the resume-a4 repo?

PS: I'm a hugo noob, so apologies if this is very trivial/silly.

TIA.

**Comment by mertbakir** [comment]
> Hi @mertbakir, thanks for putting this together.
> 
> I'm trying to follow your instructions in the README.md file and there appears to be a typo under the Start section here - https://github.com/mertbakir/resume-a4?tab=readme-ov-file#start . Step 1, says `Copy config.yaml from exampleSite to the root directory of your hugo project.` but I don't see a config.yaml file under the exampleSite. Did you mean the root directory of the resume-a4 repo?
> 
> PS: I'm a hugo noob, so apologies if this is very trivial/silly.
> 
> TIA.

Yes, the config file from the theme to your hugo project. My bad, probably a typo or I included the config.yaml in exampleSite at the time of writing that post.
